# Generated by Django 4.0.3 on 2023-11-24 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('userid', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('userpw', models.CharField(max_length=50)),
                ('username', models.TextField()),
                ('hp', models.TextField()),
                ('email', models.TextField()),
                ('gender', models.TextField()),
            ],
            options={
                'db_table': 'member',
            },
        ),
    ]
